### ISSUE TITLE
Running the model on a single image

### ISSUE THREAD

**Issue by claytonkanderson** [Nicholasli1995/EgoNet#12]
Hey Nicholasli1995,

Thanks for putting together this awesome repo, I really appreciate how thoroughly documented the setup is. 

Would it be possible to get a few hints as to how to run the model on a single image as opposed to a directory? 

I see that the data_loader in 'inference' is nearly directly from PyTorch, so it's probably my lack of experience with PyTorch that has me confused.

Separately, I also tried making my own directory and referencing it in my .yaml file, the following command still gave me an error about referencing the KITTI dataset

`python .\inference.py --cfg "../configs/single_inference_test.yml" --visualize True --batch_to_show 1`

![image](https://user-images.githubusercontent.com/30035547/155413770-223c504a-43c6-4233-9f8a-34c75ca6ce9c.png)

I was a little bit surprised to see "training" in the file not found path as I'm not asking to train -- I would expect to have to place an analogous 'test.txt' in this directory with the single test image filename, but I don't think that's currently the issue.

Thanks!
Clayton

**Comment by Nicholasli1995** [comment]
> Hey Nicholasli1995,
> 
> Thanks for putting together this awesome repo, I really appreciate how thoroughly documented the setup is.
> 
> Would it be possible to get a few hints as to how to run the model on a single image as opposed to a directory?
> 
> I see that the data_loader in 'inference' is nearly directly from PyTorch, so it's probably my lack of experience with PyTorch that has me confused.
> 
> Separately, I also tried making my own directory and referencing it in my .yaml file, the following command still gave me an error about referencing the KITTI dataset
> 
> `python .\inference.py --cfg "../configs/single_inference_test.yml" --visualize True --batch_to_show 1`
> 
> ![image](https://user-images.githubusercontent.com/30035547/155413770-223c504a-43c6-4233-9f8a-34c75ca6ce9c.png)
> 
> I was a little bit surprised to see "training" in the file not found path as I'm not asking to train -- I would expect to have to place an analogous 'test.txt' in this directory with the single test image filename, but I don't think that's currently the issue.
> 
> Thanks! Clayton

Hi Clayton, can you explain your use case that "run the model on a single image as opposed to a directory"? Do you mean you don't want to initialize the kitti directory and simply process a single image? In that case, you can modify the image list .txt file so that it only contains the name of the image you need.

The error happened because the code assumes a directory structure as detailed in https://github.com/Nicholasli1995/EgoNet/blob/master/docs/preparation.md

**Comment by claytonkanderson** [comment]
Hi Nicholasli1995, 

The intentional was to setup a pipeline so some other code could pass EgoNet an image without loading from a file but I did not fully grasp the D4LCN dependency earlier, so I think I can figure it out from here.

Thanks!
Clayton

**Comment by Nicholasli1995** [comment]
> Hi Nicholasli1995,
> 
> The intentional was to setup a pipeline so some other code could pass EgoNet an image without loading from a file but I did not fully grasp the D4LCN dependency earlier, so I think I can figure it out from here.
> 
> Thanks! Clayton

Sure. As long as there is a provided 2D region-of-interest EgoNet can be used. Any detector can be used apart from D4LCN to provide such proposals.

**Comment by claytonkanderson** [comment]
Just want to make sure, but EgoNet requires more than a 2D region of interest, right? For example, a YOLO model couldn't be used because it doesn't provide the y-rotation, 3d size, or 3d location?
