### ISSUE TITLE
About the license for this model

### ISSUE THREAD

**Issue by PINTO0309** [Nicholasli1995/EgoNet#13]
Thank you for sharing your great code. :smiley_cat:

What is the license for this model? I'd like to cite it to the repository I'm working on if possible, but I want to post the license correctly.
https://github.com/PINTO0309/PINTO_model_zoo

Thank you.

**Comment by Nicholasli1995** [comment]
> Thank you for sharing your great code. smiley_cat
> 
> What is the license for this model? I'd like to cite it to the repository I'm working on if possible, but I want to post the license correctly. https://github.com/PINTO0309/PINTO_model_zoo
> 
> Thank you.

Hi, thank you for your interest in this repo. An MIT license is used for the code. The third-party dataset (KITTI) is subject to its own license and may not grant commercial use.

**Comment by PINTO0309** [comment]
Thank you! :smile:
