### ISSUE TITLE
Training Script

### ISSUE THREAD

**Issue by kuanchih1993** [Nicholasli1995/EgoNet#5]
Thanks for your awesome work!
Could you provide some hints about how to training the EgoNet?
Thank you in advance.

**Comment by Nicholasli1995** [comment]
> Thanks for your awesome work!
> Could you provide some hints about how to training the EgoNet?
> Thank you in advance.

Hi, the training documentation is under preparation and will become available within 2 weeks. Will let you know once it's ready.

**Comment by Nicholasli1995** [comment]
> Thanks for your awesome work!
> Could you provide some hints about how to training the EgoNet?
> Thank you in advance.

The training docs are released and feel free to test them and submit potential issues.
