### ISSUE TITLE
Reproduce results on the test split

### ISSUE THREAD

**Issue by Vncois-ZXJ** [Nicholasli1995/EgoNet#7]
Thanks for your great work.
However, I have some confusion in “Reproduce results on the test split”. If I understand correctly, the inputs to the model are 2D bounding boxes which located in “../resources/test_boxes” and the outputs should be 3D bounding boxes which placed in “../output/submission/data”. However, the results I got were not 3D bounding boxes, as follows:
![Drawing](https://user-images.githubusercontent.com/68800541/128165474-f8cd4298-2263-44db-a8e3-c64379b146c6.jpg)
The results do not contain 3D information. Is it because I made a mistake somewhere?

**Comment by Nicholasli1995** [comment]
> Thanks for your great work.
> However, I have some confusion in “Reproduce results on the test split”. If I understand correctly, the inputs to the model are 2D bounding boxes which located in “../resources/test_boxes” and the outputs should be 3D bounding boxes which placed in “../output/submission/data”. However, the results I got were not 3D bounding boxes, as follows:
> ![Drawing](https://user-images.githubusercontent.com/68800541/128165474-f8cd4298-2263-44db-a8e3-c64379b146c6.jpg)
> The results do not contain 3D information. Is it because I made a mistake somewhere?

Hi, the current inference script only updates the vehicle orientation from the input boxes. If the input boxes does not have 3D location and dimension attributes, the output will be like this. This result is ready for submission for evaluating AOS. If you want to submit other attributes as well, you can use any detector that predicts 3D attributes. You can also solve for 3D location following Deep3DBox given the orientation predicted by EgoNet.

**Comment by Vncois-ZXJ** [comment]
> > 感谢您的杰出工作。
> > 但是，我对“在测试拆分上重现结果”有些困惑。如果我理解正确，模型的输入是位于“../resources/test_boxes”中的 2D 边界框，输出应该是位于“../output/submission/data”中的 3D 边界框。但是，我得到的结果不是 3D 边界框，如下所示：
> > 结果不包含 3D 信息。是因为我在某个地方犯了错误吗？
> > ![画画](https://user-images.githubusercontent.com/68800541/128165474-f8cd4298-2263-44db-a8e3-c64379b146c6.jpg)
> 
> 您好，当前的推理脚本仅从输入框中更新车辆方向。如果输入框没有3D位置和维度属性，输出会是这样。此结果已准备好提交以评估 AOS。如果您还想提交其他属性，您可以使用任何预测 3D 属性的检测器。根据 EgoNet 预测的方向，您还可以在 Deep3DBox 之后求解 3D 位置。

OK, Thanks for your reply!
